//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadMeldungenResult", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    public partial class UploadMeldungenResult : object
    {
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.UploadSchlachtdatenMeldung[] MeldungenField;
        
        private int ReferenzField;
        
        private bool UploadBeendetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.UploadSchlachtdatenMeldung[] Meldungen
        {
            get
            {
                return this.MeldungenField;
            }
            set
            {
                this.MeldungenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Referenz
        {
            get
            {
                return this.ReferenzField;
            }
            set
            {
                this.ReferenzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UploadBeendet
        {
            get
            {
                return this.UploadBeendetField;
            }
            set
            {
                this.UploadBeendetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadSchlachtdatenMeldung", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    public partial class UploadSchlachtdatenMeldung : object
    {
        
        private System.DateTime ErzeugtAmField;
        
        private bool IstFehlermeldungField;
        
        private string MeldungTextField;
        
        private int SchlachtnummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ErzeugtAm
        {
            get
            {
                return this.ErzeugtAmField;
            }
            set
            {
                this.ErzeugtAmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IstFehlermeldung
        {
            get
            {
                return this.IstFehlermeldungField;
            }
            set
            {
                this.IstFehlermeldungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MeldungText
        {
            get
            {
                return this.MeldungTextField;
            }
            set
            {
                this.MeldungTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Schlachtnummer
        {
            get
            {
                return this.SchlachtnummerField;
            }
            set
            {
                this.SchlachtnummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtdatenBearbeitungListe", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    public partial class SchlachtdatenBearbeitungListe : object
    {
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenBearbeitung[] BearbeitungenField;
        
        private System.DateTime SchlachtdatumField;
        
        private string SchlachthofBetriebsnummerField;
        
        private int SchlachthofInterneNummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenBearbeitung[] Bearbeitungen
        {
            get
            {
                return this.BearbeitungenField;
            }
            set
            {
                this.BearbeitungenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Schlachtdatum
        {
            get
            {
                return this.SchlachtdatumField;
            }
            set
            {
                this.SchlachtdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SchlachthofBetriebsnummer
        {
            get
            {
                return this.SchlachthofBetriebsnummerField;
            }
            set
            {
                this.SchlachthofBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchlachthofInterneNummer
        {
            get
            {
                return this.SchlachthofInterneNummerField;
            }
            set
            {
                this.SchlachthofInterneNummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtdatenBearbeitung", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    public partial class SchlachtdatenBearbeitung : object
    {
        
        private string BenutzerKennungField;
        
        private string BenutzerNameField;
        
        private int SchlachtnummerField;
        
        private string StationBezeichnungField;
        
        private System.DateTime ZeitpunktField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BenutzerKennung
        {
            get
            {
                return this.BenutzerKennungField;
            }
            set
            {
                this.BenutzerKennungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenutzerName
        {
            get
            {
                return this.BenutzerNameField;
            }
            set
            {
                this.BenutzerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Schlachtnummer
        {
            get
            {
                return this.SchlachtnummerField;
            }
            set
            {
                this.SchlachtnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StationBezeichnung
        {
            get
            {
                return this.StationBezeichnungField;
            }
            set
            {
                this.StationBezeichnungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Zeitpunkt
        {
            get
            {
                return this.ZeitpunktField;
            }
            set
            {
                this.ZeitpunktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Upload_SW_FaultException", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.Exceptions")]
    public partial class Upload_SW_FaultException : object
    {
        
        private string FehlermeldungField;
        
        private System.Nullable<int> SchlachtnummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fehlermeldung
        {
            get
            {
                return this.FehlermeldungField;
            }
            set
            {
                this.FehlermeldungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Schlachtnummer
        {
            get
            {
                return this.SchlachtnummerField;
            }
            set
            {
                this.SchlachtnummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtdatenSwDto", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Upload.SW")]
    public partial class SchlachtdatenSwDto : object
    {
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenSwPosDto[] SchlachtdatenSwField;
        
        private System.DateTime SchlachtdatumField;
        
        private string SchlachthofBetriebsnummerField;
        
        private int SchlachthofInterneNummerField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Merkmal[] WeitereMerkmaleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenSwPosDto[] SchlachtdatenSw
        {
            get
            {
                return this.SchlachtdatenSwField;
            }
            set
            {
                this.SchlachtdatenSwField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Schlachtdatum
        {
            get
            {
                return this.SchlachtdatumField;
            }
            set
            {
                this.SchlachtdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SchlachthofBetriebsnummer
        {
            get
            {
                return this.SchlachthofBetriebsnummerField;
            }
            set
            {
                this.SchlachthofBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SchlachthofInterneNummer
        {
            get
            {
                return this.SchlachthofInterneNummerField;
            }
            set
            {
                this.SchlachthofInterneNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Merkmal[] WeitereMerkmale
        {
            get
            {
                return this.WeitereMerkmaleField;
            }
            set
            {
                this.WeitereMerkmaleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtdatenSwPosDto", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Upload.SW")]
    public partial class SchlachtdatenSwPosDto : object
    {
        
        private string AnlieferungsnummerField;
        
        private decimal AusgeschnittenField;
        
        private decimal AusgleichsgewichtField;
        
        private decimal Bauchgewicht_AutoFOMField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Befunddaten[] BefundeField;
        
        private string BemerkungField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Beschauarten BeschauartField;
        
        private decimal BruttogewichtField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.DatenherkunftDTO DatenherkunftField;
        
        private string EichspeichernummerField;
        
        private decimal Fleischmass_AutoFOMField;
        
        private decimal Fleischmass_Hennessy_FOMField;
        
        private System.Nullable<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.GeschlechtDTO> GeschlechtField;
        
        private System.Nullable<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.HandelsklassenSW_DTO> HandelsklasseField;
        
        private decimal Indexpunkte_AutoFOMField;
        
        private string InterneKlasseField;
        
        private string KlassifizierernameField;
        
        private int KlassifizierernummerField;
        
        private decimal Kotelettgewicht_AutoFOMField;
        
        private decimal Lachsgewicht_AutoFOMField;
        
        private string LandwirtBetriebsnummerField;
        
        private int LandwirtInterneNummerField;
        
        private string LieferantBetriebsnummerField;
        
        private int LieferantInterneNummerField;
        
        private System.DateTime LieferdatumField;
        
        private decimal MFA_AutoFOMField;
        
        private decimal MFA_Bauch_AutoFOMField;
        
        private decimal MFA_Hennessy_FOMField;
        
        private decimal NettogewichtField;
        
        private int PreisgruppeField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.ProduktionsartSW_DTO ProduktionsartField;
        
        private string ProvisionaerBetriebsnummerField;
        
        private System.Nullable<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.QualitaetsprogrammSW_DTO>[] QualitaetsprogrammSWField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.NumerischerCode[] QualitaetsprogrammeField;
        
        private decimal Reflektionswert_Hennessy_FOMField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SalmonellenDTO SalmonellenField;
        
        private decimal Schinken_Schier_AutoFOMField;
        
        private decimal Schinkengewicht_AutoFOMField;
        
        private decimal Schinkenspeck_1_AutoFOMField;
        
        private decimal Schinkenspeck_2_AutoFOMField;
        
        private decimal Schinkenspeck_3_AutoFOMField;
        
        private string SchlachtbetriebBetriebsnummerField;
        
        private int SchlachtbetriebInterneNummerField;
        
        private int SchlachtnummerField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtungsartDTO SchlachtungsartField;
        
        private string SchlachtzeitField;
        
        private decimal Schulter_Schier_AutoFOMField;
        
        private decimal Schultergewicht_AutoFOMField;
        
        private decimal Speckmass_AutoFOMField;
        
        private decimal Speckmass_Hennessy_FOMField;
        
        private string SpeditionsBetriebsnummerField;
        
        private int SpeditionsInterneNummerField;
        
        private string TaetowierungField;
        
        private string TierarztKennungField;
        
        private string WagennummerField;
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Merkmal[] WeitereMerkmaleField;
        
        private decimal pH_WertField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anlieferungsnummer
        {
            get
            {
                return this.AnlieferungsnummerField;
            }
            set
            {
                this.AnlieferungsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ausgeschnitten
        {
            get
            {
                return this.AusgeschnittenField;
            }
            set
            {
                this.AusgeschnittenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ausgleichsgewicht
        {
            get
            {
                return this.AusgleichsgewichtField;
            }
            set
            {
                this.AusgleichsgewichtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Bauchgewicht_AutoFOM
        {
            get
            {
                return this.Bauchgewicht_AutoFOMField;
            }
            set
            {
                this.Bauchgewicht_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Befunddaten[] Befunde
        {
            get
            {
                return this.BefundeField;
            }
            set
            {
                this.BefundeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bemerkung
        {
            get
            {
                return this.BemerkungField;
            }
            set
            {
                this.BemerkungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Beschauarten Beschauart
        {
            get
            {
                return this.BeschauartField;
            }
            set
            {
                this.BeschauartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Bruttogewicht
        {
            get
            {
                return this.BruttogewichtField;
            }
            set
            {
                this.BruttogewichtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.DatenherkunftDTO Datenherkunft
        {
            get
            {
                return this.DatenherkunftField;
            }
            set
            {
                this.DatenherkunftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Eichspeichernummer
        {
            get
            {
                return this.EichspeichernummerField;
            }
            set
            {
                this.EichspeichernummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fleischmass_AutoFOM
        {
            get
            {
                return this.Fleischmass_AutoFOMField;
            }
            set
            {
                this.Fleischmass_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fleischmass_Hennessy_FOM
        {
            get
            {
                return this.Fleischmass_Hennessy_FOMField;
            }
            set
            {
                this.Fleischmass_Hennessy_FOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.GeschlechtDTO> Geschlecht
        {
            get
            {
                return this.GeschlechtField;
            }
            set
            {
                this.GeschlechtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.HandelsklassenSW_DTO> Handelsklasse
        {
            get
            {
                return this.HandelsklasseField;
            }
            set
            {
                this.HandelsklasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Indexpunkte_AutoFOM
        {
            get
            {
                return this.Indexpunkte_AutoFOMField;
            }
            set
            {
                this.Indexpunkte_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterneKlasse
        {
            get
            {
                return this.InterneKlasseField;
            }
            set
            {
                this.InterneKlasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Klassifizierername
        {
            get
            {
                return this.KlassifizierernameField;
            }
            set
            {
                this.KlassifizierernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Klassifizierernummer
        {
            get
            {
                return this.KlassifizierernummerField;
            }
            set
            {
                this.KlassifizierernummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Kotelettgewicht_AutoFOM
        {
            get
            {
                return this.Kotelettgewicht_AutoFOMField;
            }
            set
            {
                this.Kotelettgewicht_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Lachsgewicht_AutoFOM
        {
            get
            {
                return this.Lachsgewicht_AutoFOMField;
            }
            set
            {
                this.Lachsgewicht_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LandwirtBetriebsnummer
        {
            get
            {
                return this.LandwirtBetriebsnummerField;
            }
            set
            {
                this.LandwirtBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LandwirtInterneNummer
        {
            get
            {
                return this.LandwirtInterneNummerField;
            }
            set
            {
                this.LandwirtInterneNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LieferantBetriebsnummer
        {
            get
            {
                return this.LieferantBetriebsnummerField;
            }
            set
            {
                this.LieferantBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LieferantInterneNummer
        {
            get
            {
                return this.LieferantInterneNummerField;
            }
            set
            {
                this.LieferantInterneNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Lieferdatum
        {
            get
            {
                return this.LieferdatumField;
            }
            set
            {
                this.LieferdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MFA_AutoFOM
        {
            get
            {
                return this.MFA_AutoFOMField;
            }
            set
            {
                this.MFA_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MFA_Bauch_AutoFOM
        {
            get
            {
                return this.MFA_Bauch_AutoFOMField;
            }
            set
            {
                this.MFA_Bauch_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MFA_Hennessy_FOM
        {
            get
            {
                return this.MFA_Hennessy_FOMField;
            }
            set
            {
                this.MFA_Hennessy_FOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Nettogewicht
        {
            get
            {
                return this.NettogewichtField;
            }
            set
            {
                this.NettogewichtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Preisgruppe
        {
            get
            {
                return this.PreisgruppeField;
            }
            set
            {
                this.PreisgruppeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.ProduktionsartSW_DTO Produktionsart
        {
            get
            {
                return this.ProduktionsartField;
            }
            set
            {
                this.ProduktionsartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvisionaerBetriebsnummer
        {
            get
            {
                return this.ProvisionaerBetriebsnummerField;
            }
            set
            {
                this.ProvisionaerBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.QualitaetsprogrammSW_DTO>[] QualitaetsprogrammSW
        {
            get
            {
                return this.QualitaetsprogrammSWField;
            }
            set
            {
                this.QualitaetsprogrammSWField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.NumerischerCode[] Qualitaetsprogramme
        {
            get
            {
                return this.QualitaetsprogrammeField;
            }
            set
            {
                this.QualitaetsprogrammeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Reflektionswert_Hennessy_FOM
        {
            get
            {
                return this.Reflektionswert_Hennessy_FOMField;
            }
            set
            {
                this.Reflektionswert_Hennessy_FOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SalmonellenDTO Salmonellen
        {
            get
            {
                return this.SalmonellenField;
            }
            set
            {
                this.SalmonellenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schinken_Schier_AutoFOM
        {
            get
            {
                return this.Schinken_Schier_AutoFOMField;
            }
            set
            {
                this.Schinken_Schier_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schinkengewicht_AutoFOM
        {
            get
            {
                return this.Schinkengewicht_AutoFOMField;
            }
            set
            {
                this.Schinkengewicht_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schinkenspeck_1_AutoFOM
        {
            get
            {
                return this.Schinkenspeck_1_AutoFOMField;
            }
            set
            {
                this.Schinkenspeck_1_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schinkenspeck_2_AutoFOM
        {
            get
            {
                return this.Schinkenspeck_2_AutoFOMField;
            }
            set
            {
                this.Schinkenspeck_2_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schinkenspeck_3_AutoFOM
        {
            get
            {
                return this.Schinkenspeck_3_AutoFOMField;
            }
            set
            {
                this.Schinkenspeck_3_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SchlachtbetriebBetriebsnummer
        {
            get
            {
                return this.SchlachtbetriebBetriebsnummerField;
            }
            set
            {
                this.SchlachtbetriebBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchlachtbetriebInterneNummer
        {
            get
            {
                return this.SchlachtbetriebInterneNummerField;
            }
            set
            {
                this.SchlachtbetriebInterneNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Schlachtnummer
        {
            get
            {
                return this.SchlachtnummerField;
            }
            set
            {
                this.SchlachtnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtungsartDTO Schlachtungsart
        {
            get
            {
                return this.SchlachtungsartField;
            }
            set
            {
                this.SchlachtungsartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Schlachtzeit
        {
            get
            {
                return this.SchlachtzeitField;
            }
            set
            {
                this.SchlachtzeitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schulter_Schier_AutoFOM
        {
            get
            {
                return this.Schulter_Schier_AutoFOMField;
            }
            set
            {
                this.Schulter_Schier_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Schultergewicht_AutoFOM
        {
            get
            {
                return this.Schultergewicht_AutoFOMField;
            }
            set
            {
                this.Schultergewicht_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Speckmass_AutoFOM
        {
            get
            {
                return this.Speckmass_AutoFOMField;
            }
            set
            {
                this.Speckmass_AutoFOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Speckmass_Hennessy_FOM
        {
            get
            {
                return this.Speckmass_Hennessy_FOMField;
            }
            set
            {
                this.Speckmass_Hennessy_FOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpeditionsBetriebsnummer
        {
            get
            {
                return this.SpeditionsBetriebsnummerField;
            }
            set
            {
                this.SpeditionsBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpeditionsInterneNummer
        {
            get
            {
                return this.SpeditionsInterneNummerField;
            }
            set
            {
                this.SpeditionsInterneNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Taetowierung
        {
            get
            {
                return this.TaetowierungField;
            }
            set
            {
                this.TaetowierungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TierarztKennung
        {
            get
            {
                return this.TierarztKennungField;
            }
            set
            {
                this.TierarztKennungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wagennummer
        {
            get
            {
                return this.WagennummerField;
            }
            set
            {
                this.WagennummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Merkmal[] WeitereMerkmale
        {
            get
            {
                return this.WeitereMerkmaleField;
            }
            set
            {
                this.WeitereMerkmaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pH_Wert
        {
            get
            {
                return this.pH_WertField;
            }
            set
            {
                this.pH_WertField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Merkmal", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public partial class Merkmal : object
    {
        
        private string BezeichnungField;
        
        private string WertField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Bezeichnung
        {
            get
            {
                return this.BezeichnungField;
            }
            set
            {
                this.BezeichnungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Wert
        {
            get
            {
                return this.WertField;
            }
            set
            {
                this.WertField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalmonellenDTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public partial class SalmonellenDTO : object
    {
        
        private QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SalmonellenprobenartDTO SalmonellenprobenartField;
        
        private string SalmonellenprobenummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SalmonellenprobenartDTO Salmonellenprobenart
        {
            get
            {
                return this.SalmonellenprobenartField;
            }
            set
            {
                this.SalmonellenprobenartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Salmonellenprobenummer
        {
            get
            {
                return this.SalmonellenprobenummerField;
            }
            set
            {
                this.SalmonellenprobenummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Befunddaten", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Upload.SW")]
    public partial class Befunddaten : object
    {
        
        private int BefundcodeField;
        
        private int BefundgruppeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Befundcode
        {
            get
            {
                return this.BefundcodeField;
            }
            set
            {
                this.BefundcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Befundgruppe
        {
            get
            {
                return this.BefundgruppeField;
            }
            set
            {
                this.BefundgruppeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Beschauarten", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Upload.SW")]
    public enum Beschauarten : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Konventionell = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Visuell = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatenherkunftDTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum DatenherkunftDTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hennessy = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FoM = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutoFoM = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeschlechtDTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum GeschlechtDTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        weiblich = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        maennlich = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        immunokastriert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unkastriert = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HandelsklassenSW_DTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum HandelsklassenSW_DTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        U = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        R = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        O = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M1 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M2 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        V = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SP = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SL = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SS = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProduktionsartSW_DTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum ProduktionsartSW_DTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtSpezifiziert = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ferkel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mastschwein = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mutterschwein = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masteber = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QualitaetsprogrammSW_DTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum QualitaetsprogrammSW_DTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtSpezifiziert = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QS = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIO = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GFBW_Obsolete = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GFBY_Obsolete = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Primaschwein = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gutfleisch = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GQ = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EdekaSuedwest = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EinHerzFuerErzeuger = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EifelPremiumSchinken = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QZBW = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDS = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QsPlus = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GFBW = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GFBY = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GQS = 104,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumerischerCode", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public partial class NumerischerCode : object
    {
        
        private string NameField;
        
        private int NummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nummer
        {
            get
            {
                return this.NummerField;
            }
            set
            {
                this.NummerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtungsartDTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum SchlachtungsartDTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BetriebseigeneSchlachtung = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hausschlachtung = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Auftragsschlachtung = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notschlachtung = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schaechtung = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nottoetung = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PriorisierteSchlachtung = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalmonellenprobenartDTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum SalmonellenprobenartDTO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verordnungsprobe = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SonstigeProbe = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.ISchlachtdatenUploadSW" +
        "")]
    public interface ISchlachtdatenUploadSW
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadMeldungen/GetUploadMeldungen", ReplyAction="http://tempuri.org/IUploadMeldungen/GetUploadMeldungenResponse")]
        System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.UploadMeldungenResult> GetUploadMeldungenAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadMeldungen/GetFolgendeUploadMeldungen", ReplyAction="http://tempuri.org/IUploadMeldungen/GetFolgendeUploadMeldungenResponse")]
        System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.UploadMeldungenResult> GetFolgendeUploadMeldungenAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum, int pReferenzVorherigesErgebnis, int pWartezeitSekunden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadMeldungen/GetReferenz", ReplyAction="http://tempuri.org/IUploadMeldungen/GetReferenzResponse")]
        System.Threading.Tasks.Task<int> GetReferenzAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadMeldungen/IstUploadAktiv", ReplyAction="http://tempuri.org/IUploadMeldungen/IstUploadAktivResponse")]
        System.Threading.Tasks.Task<bool> IstUploadAktivAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadBearbeitung/UploadBearbeitung", ReplyAction="http://tempuri.org/IUploadBearbeitung/UploadBearbeitungResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Upload_SW_FaultException), Action="http://tempuri.org/IUploadBearbeitung/UploadBearbeitungUpload_SW_FaultExceptionFa" +
            "ult", Name="Upload_SW_FaultException", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.Exceptions")]
        System.Threading.Tasks.Task<bool> UploadBearbeitungAsync(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenBearbeitungListe pListe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchlachtdatenUploadSW/GetVersion", ReplyAction="http://tempuri.org/ISchlachtdatenUploadSW/GetVersionResponse")]
        System.Threading.Tasks.Task<int> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchlachtdatenUploadSW/HalloService", ReplyAction="http://tempuri.org/ISchlachtdatenUploadSW/HalloServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Upload_SW_FaultException), Action="http://tempuri.org/ISchlachtdatenUploadSW/HalloServiceUpload_SW_FaultExceptionFau" +
            "lt", Name="Upload_SW_FaultException", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.Exceptions")]
        System.Threading.Tasks.Task<string> HalloServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchlachtdatenUploadSW/UploadSwV2", ReplyAction="http://tempuri.org/ISchlachtdatenUploadSW/UploadSwV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Upload_SW_FaultException), Action="http://tempuri.org/ISchlachtdatenUploadSW/UploadSwV2Upload_SW_FaultExceptionFault" +
            "", Name="Upload_SW_FaultException", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.Exceptions")]
        System.Threading.Tasks.Task<bool> UploadSwV2Async(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenSwDto pSchlachtdatenSwDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchlachtdatenUploadSW/DeleteSchlachtdatensatzSwV2", ReplyAction="http://tempuri.org/ISchlachtdatenUploadSW/DeleteSchlachtdatensatzSwV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Upload_SW_FaultException), Action="http://tempuri.org/ISchlachtdatenUploadSW/DeleteSchlachtdatensatzSwV2Upload_SW_Fa" +
            "ultExceptionFault", Name="Upload_SW_FaultException", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.Exceptions")]
        System.Threading.Tasks.Task<bool> DeleteSchlachtdatensatzSwV2Async(string SchlachthofBetriebsnummer, System.DateTime pSchlachtdatum, int pSchlachtnummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchlachtdatenUploadSW/UpdateSchlachtdatensatzSwV2", ReplyAction="http://tempuri.org/ISchlachtdatenUploadSW/UpdateSchlachtdatensatzSwV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.Upload_SW_FaultException), Action="http://tempuri.org/ISchlachtdatenUploadSW/UpdateSchlachtdatensatzSwV2Upload_SW_Fa" +
            "ultExceptionFault", Name="Upload_SW_FaultException", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.Exceptions")]
        System.Threading.Tasks.Task<bool> UpdateSchlachtdatensatzSwV2Async(string SchlachthofBetriebsnummer, System.DateTime pSchlachtdatum, int pSchlachtnummer, QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenSwPosDto pSchlachtdatenSwPosDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISchlachtdatenUploadSWChannel : QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.ISchlachtdatenUploadSW, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SchlachtdatenUploadSWClient : System.ServiceModel.ClientBase<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.ISchlachtdatenUploadSW>, QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.ISchlachtdatenUploadSW
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SchlachtdatenUploadSWClient(EndpointConfiguration endpointConfiguration) : 
                base(SchlachtdatenUploadSWClient.GetBindingForEndpoint(endpointConfiguration), SchlachtdatenUploadSWClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchlachtdatenUploadSWClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SchlachtdatenUploadSWClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchlachtdatenUploadSWClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SchlachtdatenUploadSWClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchlachtdatenUploadSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.UploadMeldungenResult> GetUploadMeldungenAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum)
        {
            return base.Channel.GetUploadMeldungenAsync(pSchlachthofBetriebsnummer, pSchlachtdatum);
        }
        
        public System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.UploadMeldungenResult> GetFolgendeUploadMeldungenAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum, int pReferenzVorherigesErgebnis, int pWartezeitSekunden)
        {
            return base.Channel.GetFolgendeUploadMeldungenAsync(pSchlachthofBetriebsnummer, pSchlachtdatum, pReferenzVorherigesErgebnis, pWartezeitSekunden);
        }
        
        public System.Threading.Tasks.Task<int> GetReferenzAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum)
        {
            return base.Channel.GetReferenzAsync(pSchlachthofBetriebsnummer, pSchlachtdatum);
        }
        
        public System.Threading.Tasks.Task<bool> IstUploadAktivAsync(string pSchlachthofBetriebsnummer, System.DateTime pSchlachtdatum)
        {
            return base.Channel.IstUploadAktivAsync(pSchlachthofBetriebsnummer, pSchlachtdatum);
        }
        
        public System.Threading.Tasks.Task<bool> UploadBearbeitungAsync(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenBearbeitungListe pListe)
        {
            return base.Channel.UploadBearbeitungAsync(pListe);
        }
        
        public System.Threading.Tasks.Task<int> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public System.Threading.Tasks.Task<string> HalloServiceAsync()
        {
            return base.Channel.HalloServiceAsync();
        }
        
        public System.Threading.Tasks.Task<bool> UploadSwV2Async(QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenSwDto pSchlachtdatenSwDto)
        {
            return base.Channel.UploadSwV2Async(pSchlachtdatenSwDto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSchlachtdatensatzSwV2Async(string SchlachthofBetriebsnummer, System.DateTime pSchlachtdatum, int pSchlachtnummer)
        {
            return base.Channel.DeleteSchlachtdatensatzSwV2Async(SchlachthofBetriebsnummer, pSchlachtdatum, pSchlachtnummer);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSchlachtdatensatzSwV2Async(string SchlachthofBetriebsnummer, System.DateTime pSchlachtdatum, int pSchlachtnummer, QualifoodSchlachtdatenUploadSwClient.SchlachtdatenUploadSW.SchlachtdatenSwPosDto pSchlachtdatenSwPosDto)
        {
            return base.Channel.UpdateSchlachtdatensatzSwV2Async(SchlachthofBetriebsnummer, pSchlachtdatum, pSchlachtnummer, pSchlachtdatenSwPosDto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISchlachtdatenUploadSW))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpsBinding_ISchlachtdatenUploadSW))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISchlachtdatenUploadSW))
            {
                return new System.ServiceModel.EndpointAddress("https://testwebservices.qualifood.de/Klassifizierer/SchlachtdatenUploadSW.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpsBinding_ISchlachtdatenUploadSW))
            {
                return new System.ServiceModel.EndpointAddress("https://testwebservices.qualifood.de/Klassifizierer/SchlachtdatenUploadSW.svc/mex" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISchlachtdatenUploadSW,
            
            MetadataExchangeHttpsBinding_ISchlachtdatenUploadSW,
        }
    }
}
