//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MastbetriebProgramme", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Betri" +
        "ebsdaten")]
    public partial class MastbetriebProgramme : object
    {
        
        private string BalisnummerField;
        
        private string[] ProgrammeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Balisnummer
        {
            get
            {
                return this.BalisnummerField;
            }
            set
            {
                this.BalisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] Programme
        {
            get
            {
                return this.ProgrammeField;
            }
            set
            {
                this.ProgrammeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VfuParameterDto", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Vfu")]
    public partial class VfuParameterDto : object
    {
        
        private int AnzahlTiereField;
        
        private QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuBefundDto[] BefundeField;
        
        private string LandwirtBetriebsnummerField;
        
        private bool QsFreilandhaltungField;
        
        private int SalmonellenKategorieField;
        
        private bool VfuFreigabeSystemField;
        
        private bool VfuFreigabeVeterinaerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnzahlTiere
        {
            get
            {
                return this.AnzahlTiereField;
            }
            set
            {
                this.AnzahlTiereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuBefundDto[] Befunde
        {
            get
            {
                return this.BefundeField;
            }
            set
            {
                this.BefundeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LandwirtBetriebsnummer
        {
            get
            {
                return this.LandwirtBetriebsnummerField;
            }
            set
            {
                this.LandwirtBetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool QsFreilandhaltung
        {
            get
            {
                return this.QsFreilandhaltungField;
            }
            set
            {
                this.QsFreilandhaltungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalmonellenKategorie
        {
            get
            {
                return this.SalmonellenKategorieField;
            }
            set
            {
                this.SalmonellenKategorieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VfuFreigabeSystem
        {
            get
            {
                return this.VfuFreigabeSystemField;
            }
            set
            {
                this.VfuFreigabeSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VfuFreigabeVeterinaer
        {
            get
            {
                return this.VfuFreigabeVeterinaerField;
            }
            set
            {
                this.VfuFreigabeVeterinaerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VfuBefundDto", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Vfu")]
    public partial class VfuBefundDto : object
    {
        
        private float HaeufigkeitLwProzentField;
        
        private float HaeufigkeitShProzentField;
        
        private QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuBefundLokalisationEnum LokalisationField;
        
        private QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuBefundStatusEnum StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float HaeufigkeitLwProzent
        {
            get
            {
                return this.HaeufigkeitLwProzentField;
            }
            set
            {
                this.HaeufigkeitLwProzentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float HaeufigkeitShProzent
        {
            get
            {
                return this.HaeufigkeitShProzentField;
            }
            set
            {
                this.HaeufigkeitShProzentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuBefundLokalisationEnum Lokalisation
        {
            get
            {
                return this.LokalisationField;
            }
            set
            {
                this.LokalisationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuBefundStatusEnum Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VfuBefundLokalisationEnum", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Vfu")]
    public enum VfuBefundLokalisationEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Herz = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lunge = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Leber = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brustfell = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Niere = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VfuBefundStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Vfu")]
    public enum VfuBefundStatusEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gruen = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gelb = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rot = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StammdatenRolle", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum StammdatenRolle : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schlachthof = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schlachtbetrieb = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lieferant = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spediteur = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Landwirt = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ferkelerzeuger = 26,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stammdaten", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public partial class Stammdaten : object
    {
        
        private string AnschriftZusatzField;
        
        private string BetriebsnummerField;
        
        private string EmailField;
        
        private string FaxField;
        
        private string HandyField;
        
        private string LandField;
        
        private string Name1Field;
        
        private string Name2Field;
        
        private string OrtField;
        
        private string PostleitzahlField;
        
        private string StrasseField;
        
        private string TelefonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AnschriftZusatz
        {
            get
            {
                return this.AnschriftZusatzField;
            }
            set
            {
                this.AnschriftZusatzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Betriebsnummer
        {
            get
            {
                return this.BetriebsnummerField;
            }
            set
            {
                this.BetriebsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Handy
        {
            get
            {
                return this.HandyField;
            }
            set
            {
                this.HandyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Land
        {
            get
            {
                return this.LandField;
            }
            set
            {
                this.LandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name1
        {
            get
            {
                return this.Name1Field;
            }
            set
            {
                this.Name1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name2
        {
            get
            {
                return this.Name2Field;
            }
            set
            {
                this.Name2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ort
        {
            get
            {
                return this.OrtField;
            }
            set
            {
                this.OrtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Postleitzahl
        {
            get
            {
                return this.PostleitzahlField;
            }
            set
            {
                this.PostleitzahlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Strasse
        {
            get
            {
                return this.StrasseField;
            }
            set
            {
                this.StrasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.IBetriebsdatenService")]
    public interface IBetriebsdatenService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/GetVersion", ReplyAction="http://tempuri.org/IBetriebsdatenService/GetVersionResponse")]
        System.Threading.Tasks.Task<int> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/GetMastbetriebProgramme", ReplyAction="http://tempuri.org/IBetriebsdatenService/GetMastbetriebProgrammeResponse")]
        System.Threading.Tasks.Task<string[]> GetMastbetriebProgrammeAsync(string Balisnummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/GetManyMastbetriebProgramme", ReplyAction="http://tempuri.org/IBetriebsdatenService/GetManyMastbetriebProgrammeResponse")]
        System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.MastbetriebProgramme[]> GetManyMastbetriebProgrammeAsync(string[] Balisnummern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/GetMastbetriebVfuParameter", ReplyAction="http://tempuri.org/IBetriebsdatenService/GetMastbetriebVfuParameterResponse")]
        System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuParameterDto> GetMastbetriebVfuParameterAsync(string SchlachthofBetriebsnummer, string LandwirtBetriebsnummer, int TierAnzahl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/SetMastbetriebVfuFreigabe", ReplyAction="http://tempuri.org/IBetriebsdatenService/SetMastbetriebVfuFreigabeResponse")]
        System.Threading.Tasks.Task SetMastbetriebVfuFreigabeAsync(string SchlachthofBetriebsnummer, string LandwirtBetriebsnummer, bool FreigabeVeterinaer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/SendStammdaten", ReplyAction="http://tempuri.org/IBetriebsdatenService/SendStammdatenResponse")]
        System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.Stammdaten[]> SendStammdatenAsync(QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.StammdatenRolle Rolle, QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.Stammdaten[] StammdatenListe, string DatenQuelleBezeichnung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetriebsdatenService/PruefeKomponentenVersion", ReplyAction="http://tempuri.org/IBetriebsdatenService/PruefeKomponentenVersionResponse")]
        System.Threading.Tasks.Task<string> PruefeKomponentenVersionAsync(string Standort, string Arbeitsplatz, string Komponente, string Version);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IBetriebsdatenServiceChannel : QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.IBetriebsdatenService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BetriebsdatenServiceClient : System.ServiceModel.ClientBase<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.IBetriebsdatenService>, QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.IBetriebsdatenService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BetriebsdatenServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BetriebsdatenServiceClient.GetBindingForEndpoint(endpointConfiguration), BetriebsdatenServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BetriebsdatenServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BetriebsdatenServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BetriebsdatenServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BetriebsdatenServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BetriebsdatenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetMastbetriebProgrammeAsync(string Balisnummer)
        {
            return base.Channel.GetMastbetriebProgrammeAsync(Balisnummer);
        }
        
        public System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.MastbetriebProgramme[]> GetManyMastbetriebProgrammeAsync(string[] Balisnummern)
        {
            return base.Channel.GetManyMastbetriebProgrammeAsync(Balisnummern);
        }
        
        public System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.VfuParameterDto> GetMastbetriebVfuParameterAsync(string SchlachthofBetriebsnummer, string LandwirtBetriebsnummer, int TierAnzahl)
        {
            return base.Channel.GetMastbetriebVfuParameterAsync(SchlachthofBetriebsnummer, LandwirtBetriebsnummer, TierAnzahl);
        }
        
        public System.Threading.Tasks.Task SetMastbetriebVfuFreigabeAsync(string SchlachthofBetriebsnummer, string LandwirtBetriebsnummer, bool FreigabeVeterinaer)
        {
            return base.Channel.SetMastbetriebVfuFreigabeAsync(SchlachthofBetriebsnummer, LandwirtBetriebsnummer, FreigabeVeterinaer);
        }
        
        public System.Threading.Tasks.Task<QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.Stammdaten[]> SendStammdatenAsync(QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.StammdatenRolle Rolle, QualifoodSchlachtdatenUploadSwClient.BetriebsdatenService.Stammdaten[] StammdatenListe, string DatenQuelleBezeichnung)
        {
            return base.Channel.SendStammdatenAsync(Rolle, StammdatenListe, DatenQuelleBezeichnung);
        }
        
        public System.Threading.Tasks.Task<string> PruefeKomponentenVersionAsync(string Standort, string Arbeitsplatz, string Komponente, string Version)
        {
            return base.Channel.PruefeKomponentenVersionAsync(Standort, Arbeitsplatz, Komponente, Version);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBetriebsdatenService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpsBinding_IBetriebsdatenService))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBetriebsdatenService))
            {
                return new System.ServiceModel.EndpointAddress("https://testwebservices.qualifood.de/Stammdaten/BetriebsdatenService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpsBinding_IBetriebsdatenService))
            {
                return new System.ServiceModel.EndpointAddress("https://testwebservices.qualifood.de/Stammdaten/BetriebsdatenService.svc/mex");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBetriebsdatenService,
            
            MetadataExchangeHttpsBinding_IBetriebsdatenService,
        }
    }
}
